name = "Dictionaries"
uuid = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
authors = ["Andy Ferris <ferris.andy@gmail.com>"]
version = "0.3.10"

[deps]
Indexing = "313cdc1a-70c2-5d6a-ae34-0150d3930a38"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Indexing = "1.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
